Algoritmo "priprog"

Var
    num_1, num_2: inteiro
    nota_1 : real
    nome : caractere

Inicio
      //num_1 <- 3
      //num_2 <- 7
      escreval ("Digite primeiro número: ")
      leia (num_1)
      escreval ("Digite próximo número: ")
      leia (num_2)
      escreval ("O primeiro número informado foi: ", num_1)
      escreval ("O segundo número informado foi: ", num_2)

Fimalgoritmo